#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercarpp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="appmercar")]
	public partial class ConexionCompraDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionCompraDataContext() : 
				base(global::Mercarpp.Properties.Settings.Default.appmercarConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionCompraDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionCompraDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionCompraDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionCompraDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarCompra")]
		public int ActualizarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProducto", DbType="VarChar(50)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="VarChar(50)")] string cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuento", DbType="VarChar(50)")] string descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Int")] System.Nullable<int> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lugar", DbType="VarChar(50)")] string lugar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_De_Compra, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_Producto", DbType="VarChar(40)")] string tipo_Producto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(80)")] string observaciones)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, idProducto, cedula, nombreProducto, cantidad, descuento, precio, lugar, fecha_De_Compra, tipo_Producto, observaciones);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCompra")]
		public ISingleResult<BuscarCompraResult> BuscarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProducto", DbType="VarChar(50)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_De_Compra)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreProducto, fecha_De_Compra);
			return ((ISingleResult<BuscarCompraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCompra")]
		public int EliminarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCompra")]
		public int InsertarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProducto", DbType="VarChar(50)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="VarChar(50)")] string cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuento", DbType="VarChar(50)")] string descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Int")] System.Nullable<int> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lugar", DbType="VarChar(50)")] string lugar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_De_Compra, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_Producto", DbType="VarChar(40)")] string tipo_Producto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(80)")] string observaciones)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, cedula, nombreProducto, cantidad, descuento, precio, lugar, fecha_De_Compra, tipo_Producto, observaciones);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarCompra")]
		public ISingleResult<ListarCompraResult> ListarCompra()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarCompraResult>)(result.ReturnValue));
		}
	}
	
	public partial class BuscarCompraResult
	{
		
		private int _id;
		
		private System.Nullable<int> _idProducto;
		
		private System.Nullable<int> _Cedula;
		
		private string _NombreProducto;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<int> _Descuento;
		
		private System.Nullable<int> _Precio;
		
		private string _Lugar;
		
		private string _fecha_De_Compra;
		
		private string _Tipo_Producto;
		
		private string _Observaciones;
		
		public BuscarCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int")]
		public System.Nullable<int> idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="Int")]
		public System.Nullable<int> Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(50)")]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Int")]
		public System.Nullable<int> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Int")]
		public System.Nullable<int> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="VarChar(50)")]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this._Lugar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_De_Compra", DbType="VarChar(50)")]
		public string fecha_De_Compra
		{
			get
			{
				return this._fecha_De_Compra;
			}
			set
			{
				if ((this._fecha_De_Compra != value))
				{
					this._fecha_De_Compra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Producto", DbType="VarChar(50)")]
		public string Tipo_Producto
		{
			get
			{
				return this._Tipo_Producto;
			}
			set
			{
				if ((this._Tipo_Producto != value))
				{
					this._Tipo_Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(80)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this._Observaciones = value;
				}
			}
		}
	}
	
	public partial class ListarCompraResult
	{
		
		private int _id;
		
		private System.Nullable<int> _idProducto;
		
		private System.Nullable<int> _Cedula;
		
		private string _NombreProducto;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<int> _Descuento;
		
		private System.Nullable<int> _Precio;
		
		private string _Lugar;
		
		private string _fecha_De_Compra;
		
		private string _Tipo_Producto;
		
		private string _Observaciones;
		
		public ListarCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int")]
		public System.Nullable<int> idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="Int")]
		public System.Nullable<int> Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(50)")]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Int")]
		public System.Nullable<int> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Int")]
		public System.Nullable<int> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="VarChar(50)")]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this._Lugar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_De_Compra", DbType="VarChar(50)")]
		public string fecha_De_Compra
		{
			get
			{
				return this._fecha_De_Compra;
			}
			set
			{
				if ((this._fecha_De_Compra != value))
				{
					this._fecha_De_Compra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Producto", DbType="VarChar(50)")]
		public string Tipo_Producto
		{
			get
			{
				return this._Tipo_Producto;
			}
			set
			{
				if ((this._Tipo_Producto != value))
				{
					this._Tipo_Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(80)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this._Observaciones = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
